### ISSUE TITLE
Find the unicode character for AltGr+F -> Shift+B

### ISSUE THREAD

**Issue by marcbal** [marcbal/Printable-AZERTY-NF#1]

**Comment by springcomp** [comment]
Is this currency sign really assigned?
As per a [late draft](https://lafibre.info/images/doc/201706_afnor_nouveau_clavier_NF_Z_71-300.pdf), this does not seem to be the case.
I mean, all Unicode code points from this document are already accounted for...

**Comment by marcbal** [comment]
Thanks for the link !
At page 16, I see 2 entries for the key B in the monetary mode
- "Bitcoin symbol" at group 1 / level 1 (this Unicode entry probably didn't exist at the date of this draft, but now this is `₿`)
- Thai Currency Symbol Baht `฿` at group 1 / level 2 (shift)

So it seems that the [image initially used to make the layout](http://norme-azerty.fr/img/monetary_level.png) doesn't correspond to the information stated above.

**Comment by springcomp** [comment]
Good catch, thanks for the clarification.
I will [correct the layout](https://github.com/tbolon/optimized-azerty-win/issues/39) immediately, as I’m using the BAHT symbol on Level 1 instead of Level 2.

**Comment by marcbal** [comment]
Nice,
On my side, I will add the balt symbol in the layout
